name: Postgres DB Push
on:
  push:
    branches:
      - master
    paths:
      - "database/prisma/**"
jobs:
  prisma-job-user:
    runs-on: ubuntu-latest
    outputs:
      job-status: ${{ job.status }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - uses: okteto/context@latest
        with:
          token: ${{ secrets.OKTETO_TOKEN }}
      
      - name: Create development environments namespace
        uses: okteto/namespace@latest
        with:
          namespace: prod-szwtomas
      
      - name: Build image and deploy 
        uses: ./.github/actions
        with:
          tag: okteto.dev/prisma-job-user:${{ github.sha }}
          file: database/prisma/Dockerfile
          sha: ${{ github.sha }}
          okteto_yml: okteto_database.yml
          k8s_deployment_file: database/prisma/kubernetes/prisma-job-user.yml

