name: Deployment to Okteto
on:
  push:
    branches:
      - master
jobs:
  okteto-deployment:
    runs-on: ubuntu-latest
    needs: prisma-job-user
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - uses: okteto/context@latest
        with:
          token: ${{ secrets.OKTETO_TOKEN }}
      
      - name: Create development environments namespace
        uses: okteto/namespace@latest
        with:
          namespace: prod-szwtomas
      
      - name: Build image and deploy 
        uses: ./.github/actions
        with:
          tag: okteto.dev/user-service:${{ github.sha }}
          file: Dockerfile
          sha: ${{ github.sha }}
          okteto_yml: okteto_service.yml
          k8s_deployment_file: kubernetes/deployment.yml
