name: User Service - Tests, Linter and Deployment to Okteto
on:
  push:
    branches:
      - master
jobs:
  code-quality:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Build docker image
        run: docker build --no-cache --progress=plain -t user-service .
      - name: Run linter
        run: docker run user-service npm run lint
  tests-code-coverage:
    needs: code-quality
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Build Docker Image
        run: docker build --no-cache --progress=plain -t user-service .
      - name: Run Unit Tests
        run: docker run user-service npm test
  okteto-deployment:
    runs-on: ubuntu-latest
    needs: tests-code-coverage
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - uses: okteto/context@latest
        with:
          token: ${{ secrets.OKTETO_TOKEN }}
      - name: "Build"
        uses: okteto/build@latest
        with:
          file: /docker/Dockerfile
